// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGroupMember(arg1) {
  return window['go']['main']['App']['AddGroupMember'](arg1);
}

export function AddRepo(arg1) {
  return window['go']['main']['App']['AddRepo'](arg1);
}

export function ApplyGroup(arg1, arg2) {
  return window['go']['main']['App']['ApplyGroup'](arg1, arg2);
}

export function ArchiveWorkspace(arg1, arg2) {
  return window['go']['main']['App']['ArchiveWorkspace'](arg1, arg2);
}

export function CommitAndPush(arg1) {
  return window['go']['main']['App']['CommitAndPush'](arg1);
}

export function CreateAlias(arg1) {
  return window['go']['main']['App']['CreateAlias'](arg1);
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function CreatePullRequest(arg1) {
  return window['go']['main']['App']['CreatePullRequest'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function CreateWorkspaceTerminal(arg1) {
  return window['go']['main']['App']['CreateWorkspaceTerminal'](arg1);
}

export function DeleteAlias(arg1) {
  return window['go']['main']['App']['DeleteAlias'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteReviewComment(arg1) {
  return window['go']['main']['App']['DeleteReviewComment'](arg1);
}

export function EditReviewComment(arg1) {
  return window['go']['main']['App']['EditReviewComment'](arg1);
}

export function GeneratePullRequestText(arg1) {
  return window['go']['main']['App']['GeneratePullRequestText'](arg1);
}

export function GetBranchDiffSummary(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetBranchDiffSummary'](arg1, arg2, arg3, arg4);
}

export function GetBranchFileDiff(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetBranchFileDiff'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetCurrentGitHubUser(arg1) {
  return window['go']['main']['App']['GetCurrentGitHubUser'](arg1);
}

export function GetGroup(arg1) {
  return window['go']['main']['App']['GetGroup'](arg1);
}

export function GetPullRequestReviews(arg1) {
  return window['go']['main']['App']['GetPullRequestReviews'](arg1);
}

export function GetPullRequestStatus(arg1) {
  return window['go']['main']['App']['GetPullRequestStatus'](arg1);
}

export function GetRepoDiff(arg1, arg2) {
  return window['go']['main']['App']['GetRepoDiff'](arg1, arg2);
}

export function GetRepoDiffSummary(arg1, arg2) {
  return window['go']['main']['App']['GetRepoDiffSummary'](arg1, arg2);
}

export function GetRepoFileDiff(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetRepoFileDiff'](arg1, arg2, arg3, arg4, arg5);
}

export function GetRepoLocalStatus(arg1) {
  return window['go']['main']['App']['GetRepoLocalStatus'](arg1);
}

export function GetSessiondStatus() {
  return window['go']['main']['App']['GetSessiondStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTerminalBacklog(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTerminalBacklog'](arg1, arg2, arg3);
}

export function GetTerminalBootstrap(arg1, arg2) {
  return window['go']['main']['App']['GetTerminalBootstrap'](arg1, arg2);
}

export function GetTerminalSnapshot(arg1, arg2) {
  return window['go']['main']['App']['GetTerminalSnapshot'](arg1, arg2);
}

export function GetTrackedPullRequest(arg1) {
  return window['go']['main']['App']['GetTrackedPullRequest'](arg1);
}

export function GetWorkspaceTerminalStatus(arg1, arg2) {
  return window['go']['main']['App']['GetWorkspaceTerminalStatus'](arg1, arg2);
}

export function ListAliases() {
  return window['go']['main']['App']['ListAliases']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListRemotes(arg1) {
  return window['go']['main']['App']['ListRemotes'](arg1);
}

export function ListWorkspaceSnapshots(arg1) {
  return window['go']['main']['App']['ListWorkspaceSnapshots'](arg1);
}

export function LogTerminalDebug(arg1) {
  return window['go']['main']['App']['LogTerminalDebug'](arg1);
}

export function OpenDirectoryDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1, arg2);
}

export function RemoveGroupMember(arg1) {
  return window['go']['main']['App']['RemoveGroupMember'](arg1);
}

export function RemoveRepo(arg1) {
  return window['go']['main']['App']['RemoveRepo'](arg1);
}

export function RemoveWorkspace(arg1) {
  return window['go']['main']['App']['RemoveWorkspace'](arg1);
}

export function RenameWorkspace(arg1, arg2) {
  return window['go']['main']['App']['RenameWorkspace'](arg1, arg2);
}

export function ReplyToReviewComment(arg1) {
  return window['go']['main']['App']['ReplyToReviewComment'](arg1);
}

export function ResizeWorkspaceTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResizeWorkspaceTerminal'](arg1, arg2, arg3, arg4);
}

export function ResolveReviewThread(arg1) {
  return window['go']['main']['App']['ResolveReviewThread'](arg1);
}

export function RestartSessiond() {
  return window['go']['main']['App']['RestartSessiond']();
}

export function SendPullRequestReviewsToTerminal(arg1) {
  return window['go']['main']['App']['SendPullRequestReviewsToTerminal'](arg1);
}

export function SetDefaultSetting(arg1, arg2) {
  return window['go']['main']['App']['SetDefaultSetting'](arg1, arg2);
}

export function StartWorkspaceTerminal(arg1, arg2) {
  return window['go']['main']['App']['StartWorkspaceTerminal'](arg1, arg2);
}

export function StopWorkspaceTerminal(arg1, arg2) {
  return window['go']['main']['App']['StopWorkspaceTerminal'](arg1, arg2);
}

export function UnarchiveWorkspace(arg1) {
  return window['go']['main']['App']['UnarchiveWorkspace'](arg1);
}

export function UpdateAlias(arg1) {
  return window['go']['main']['App']['UpdateAlias'](arg1);
}

export function UpdateGroup(arg1) {
  return window['go']['main']['App']['UpdateGroup'](arg1);
}

export function WriteWorkspaceTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteWorkspaceTerminal'](arg1, arg2, arg3);
}
