// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {worksetapi} from '../models';

export function AddGroupMember(arg1:main.GroupMemberRequest):Promise<worksetapi.GroupJSON>;

export function AddRepo(arg1:main.RepoAddRequest):Promise<main.RepoAddResponse>;

export function ApplyGroup(arg1:string,arg2:string):Promise<worksetapi.GroupApplyResultJSON>;

export function ArchiveWorkspace(arg1:string,arg2:string):Promise<worksetapi.WorkspaceRefJSON>;

export function CreateAlias(arg1:main.AliasUpsertRequest):Promise<worksetapi.AliasMutationResultJSON>;

export function CreateGroup(arg1:main.GroupUpsertRequest):Promise<worksetapi.GroupJSON>;

export function CreateWorkspace(arg1:main.WorkspaceCreateRequest):Promise<main.WorkspaceCreateResponse>;

export function DeleteAlias(arg1:string):Promise<worksetapi.AliasMutationResultJSON>;

export function DeleteGroup(arg1:string):Promise<worksetapi.AliasMutationResultJSON>;

export function GetAgentAvailability():Promise<Record<string, boolean>>;

export function GetGroup(arg1:string):Promise<worksetapi.GroupJSON>;

export function GetRepoDiff(arg1:string,arg2:string):Promise<main.RepoDiffSnapshot>;

export function GetRepoDiffSummary(arg1:string,arg2:string):Promise<main.RepoDiffSummary>;

export function GetRepoFileDiff(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.RepoFileDiffSnapshot>;

export function GetSettings():Promise<main.SettingsSnapshot>;

export function ListAliases():Promise<Array<worksetapi.AliasJSON>>;

export function ListGroups():Promise<Array<worksetapi.GroupSummaryJSON>>;

export function ListWorkspaceSnapshots(arg1:boolean):Promise<Array<main.WorkspaceSnapshot>>;

export function OpenDirectoryDialog(arg1:string,arg2:string):Promise<string>;

export function RemoveGroupMember(arg1:main.GroupMemberRequest):Promise<worksetapi.GroupJSON>;

export function RemoveRepo(arg1:main.RepoRemoveRequest):Promise<worksetapi.RepoRemoveResultJSON>;

export function RemoveWorkspace(arg1:string):Promise<worksetapi.WorkspaceDeleteResultJSON>;

export function RenameWorkspace(arg1:string,arg2:string):Promise<worksetapi.WorkspaceRefJSON>;

export function ResizeWorkspaceTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetDefaultSetting(arg1:string,arg2:string):Promise<worksetapi.ConfigSetResultJSON>;

export function StartWorkspaceTerminal(arg1:string):Promise<void>;

export function StopWorkspaceTerminal(arg1:string):Promise<void>;

export function UnarchiveWorkspace(arg1:string):Promise<worksetapi.WorkspaceRefJSON>;

export function UpdateAlias(arg1:main.AliasUpsertRequest):Promise<worksetapi.AliasMutationResultJSON>;

export function UpdateGroup(arg1:main.GroupUpsertRequest):Promise<worksetapi.GroupJSON>;

export function UpdateRepoRemotes(arg1:main.RepoRemotesUpdateRequest):Promise<worksetapi.RepoRemotesUpdateResultJSON>;

export function WriteWorkspaceTerminal(arg1:string,arg2:string):Promise<void>;
