// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGroupMember(arg1) {
  return window['go']['main']['App']['AddGroupMember'](arg1);
}

export function AddRepo(arg1) {
  return window['go']['main']['App']['AddRepo'](arg1);
}

export function ApplyGroup(arg1, arg2) {
  return window['go']['main']['App']['ApplyGroup'](arg1, arg2);
}

export function ArchiveWorkspace(arg1, arg2) {
  return window['go']['main']['App']['ArchiveWorkspace'](arg1, arg2);
}

export function CreateAlias(arg1) {
  return window['go']['main']['App']['CreateAlias'](arg1);
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function DeleteAlias(arg1) {
  return window['go']['main']['App']['DeleteAlias'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function GetGroup(arg1) {
  return window['go']['main']['App']['GetGroup'](arg1);
}

export function GetRepoDiff(arg1, arg2) {
  return window['go']['main']['App']['GetRepoDiff'](arg1, arg2);
}

export function GetRepoDiffSummary(arg1, arg2) {
  return window['go']['main']['App']['GetRepoDiffSummary'](arg1, arg2);
}

export function GetRepoFileDiff(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetRepoFileDiff'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListAliases() {
  return window['go']['main']['App']['ListAliases']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListWorkspaceSnapshots(arg1) {
  return window['go']['main']['App']['ListWorkspaceSnapshots'](arg1);
}

export function OpenDirectoryDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1, arg2);
}

export function RemoveGroupMember(arg1) {
  return window['go']['main']['App']['RemoveGroupMember'](arg1);
}

export function RemoveRepo(arg1) {
  return window['go']['main']['App']['RemoveRepo'](arg1);
}

export function RemoveWorkspace(arg1) {
  return window['go']['main']['App']['RemoveWorkspace'](arg1);
}

export function RenameWorkspace(arg1, arg2) {
  return window['go']['main']['App']['RenameWorkspace'](arg1, arg2);
}

export function ResizeWorkspaceTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeWorkspaceTerminal'](arg1, arg2, arg3);
}

export function SetDefaultSetting(arg1, arg2) {
  return window['go']['main']['App']['SetDefaultSetting'](arg1, arg2);
}

export function StartWorkspaceTerminal(arg1) {
  return window['go']['main']['App']['StartWorkspaceTerminal'](arg1);
}

export function StopWorkspaceTerminal(arg1) {
  return window['go']['main']['App']['StopWorkspaceTerminal'](arg1);
}

export function UnarchiveWorkspace(arg1) {
  return window['go']['main']['App']['UnarchiveWorkspace'](arg1);
}

export function UpdateAlias(arg1) {
  return window['go']['main']['App']['UpdateAlias'](arg1);
}

export function UpdateGroup(arg1) {
  return window['go']['main']['App']['UpdateGroup'](arg1);
}

export function UpdateRepoRemotes(arg1) {
  return window['go']['main']['App']['UpdateRepoRemotes'](arg1);
}

export function WriteWorkspaceTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteWorkspaceTerminal'](arg1, arg2);
}
