// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {worksetapi} from '../models';

export function AckWorkspaceTerminal(arg1:string,arg2:string,arg3:number):Promise<void>;

export function AddGroupMember(arg1:main.GroupMemberRequest):Promise<worksetapi.GroupJSON>;

export function AddRepo(arg1:main.RepoAddRequest):Promise<main.RepoAddResponse>;

export function ApplyGroup(arg1:string,arg2:string):Promise<worksetapi.GroupApplyResultJSON>;

export function ArchiveWorkspace(arg1:string,arg2:string):Promise<worksetapi.WorkspaceRefJSON>;

export function CheckAgentStatus(arg1:main.AgentCheckRequest):Promise<worksetapi.AgentCLIStatusJSON>;

export function CommitAndPush(arg1:main.CommitAndPushRequest):Promise<worksetapi.CommitAndPushResultJSON>;

export function CreateAlias(arg1:main.AliasUpsertRequest):Promise<worksetapi.AliasMutationResultJSON>;

export function CreateGroup(arg1:main.GroupUpsertRequest):Promise<worksetapi.GroupJSON>;

export function CreatePullRequest(arg1:main.PullRequestCreateRequest):Promise<worksetapi.PullRequestCreatedJSON>;

export function CreateWorkspace(arg1:main.WorkspaceCreateRequest):Promise<main.WorkspaceCreateResponse>;

export function CreateWorkspaceTerminal(arg1:string):Promise<main.TerminalCreatePayload>;

export function DeleteAlias(arg1:string):Promise<worksetapi.AliasMutationResultJSON>;

export function DeleteGroup(arg1:string):Promise<worksetapi.AliasMutationResultJSON>;

export function DeleteReviewComment(arg1:main.DeleteReviewCommentRequest):Promise<void>;

export function DisconnectGitHub():Promise<void>;

export function EditReviewComment(arg1:main.EditReviewCommentRequest):Promise<worksetapi.PullRequestReviewCommentJSON>;

export function GeneratePullRequestText(arg1:main.PullRequestGenerateRequest):Promise<worksetapi.PullRequestGeneratedJSON>;

export function GetAppVersion():Promise<main.AppVersion>;

export function GetBranchDiffSummary(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.RepoDiffSummary>;

export function GetBranchFileDiff(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<main.RepoFileDiffSnapshot>;

export function GetCurrentGitHubUser(arg1:main.GitHubUserRequest):Promise<worksetapi.GitHubUserJSON>;

export function GetGitHubAuthInfo():Promise<worksetapi.GitHubAuthInfoJSON>;

export function GetGitHubAuthStatus():Promise<worksetapi.GitHubAuthStatusJSON>;

export function GetGroup(arg1:string):Promise<worksetapi.GroupJSON>;

export function GetPullRequestReviews(arg1:main.PullRequestReviewsRequest):Promise<main.PullRequestReviewCommentsPayload>;

export function GetPullRequestStatus(arg1:main.PullRequestStatusRequest):Promise<main.PullRequestStatusPayload>;

export function GetRepoDiff(arg1:string,arg2:string):Promise<main.RepoDiffSnapshot>;

export function GetRepoDiffSummary(arg1:string,arg2:string):Promise<main.RepoDiffSummary>;

export function GetRepoFileDiff(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.RepoFileDiffSnapshot>;

export function GetRepoLocalStatus(arg1:main.RepoLocalStatusRequest):Promise<worksetapi.RepoLocalStatusJSON>;

export function GetSessiondStatus():Promise<main.SessiondStatus>;

export function GetSettings():Promise<main.SettingsSnapshot>;

export function GetTerminalBacklog(arg1:string,arg2:string,arg3:number):Promise<main.TerminalBacklogPayload>;

export function GetTerminalBootstrap(arg1:string,arg2:string):Promise<main.TerminalBootstrapPayload>;

export function GetTerminalSnapshot(arg1:string,arg2:string):Promise<main.TerminalSnapshotPayload>;

export function GetTrackedPullRequest(arg1:main.PullRequestTrackedRequest):Promise<worksetapi.PullRequestTrackedJSON>;

export function GetWorkspaceTerminalStatus(arg1:string,arg2:string):Promise<main.TerminalStatusPayload>;

export function ListAliases():Promise<Array<worksetapi.AliasJSON>>;

export function ListGroups():Promise<Array<worksetapi.GroupSummaryJSON>>;

export function ListRemotes(arg1:main.ListRemotesRequest):Promise<Array<worksetapi.RemoteInfoJSON>>;

export function ListWorkspaceSnapshots(arg1:main.WorkspaceSnapshotRequest):Promise<Array<main.WorkspaceSnapshot>>;

export function LogTerminalDebug(arg1:main.TerminalDebugPayload):Promise<void>;

export function OpenDirectoryDialog(arg1:string,arg2:string):Promise<string>;

export function OpenFileDialog(arg1:string,arg2:string):Promise<string>;

export function RemoveGroupMember(arg1:main.GroupMemberRequest):Promise<worksetapi.GroupJSON>;

export function RemoveRepo(arg1:main.RepoRemoveRequest):Promise<worksetapi.RepoRemoveResultJSON>;

export function RemoveWorkspace(arg1:main.WorkspaceRemoveRequest):Promise<worksetapi.WorkspaceDeleteResultJSON>;

export function RenameWorkspace(arg1:string,arg2:string):Promise<worksetapi.WorkspaceRefJSON>;

export function ReplyToReviewComment(arg1:main.ReplyToReviewCommentRequest):Promise<worksetapi.PullRequestReviewCommentJSON>;

export function ResizeWorkspaceTerminal(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function ResolveReviewThread(arg1:main.ResolveReviewThreadRequest):Promise<boolean>;

export function RestartSessiond():Promise<main.SessiondStatus>;

export function SendPullRequestReviewsToTerminal(arg1:main.PullRequestReviewsRequest):Promise<void>;

export function SetAgentCLIPath(arg1:main.AgentCLIPathRequest):Promise<worksetapi.AgentCLIStatusJSON>;

export function SetDefaultSetting(arg1:string,arg2:string):Promise<worksetapi.ConfigSetResultJSON>;

export function SetGitHubAuthMode(arg1:main.GitHubAuthModeRequest):Promise<worksetapi.GitHubAuthInfoJSON>;

export function SetGitHubCLIPath(arg1:main.GitHubCLIPathRequest):Promise<worksetapi.GitHubAuthInfoJSON>;

export function SetGitHubToken(arg1:main.GitHubTokenRequest):Promise<worksetapi.GitHubAuthStatusJSON>;

export function StartWorkspaceTerminal(arg1:string,arg2:string):Promise<void>;

export function StopWorkspaceTerminal(arg1:string,arg2:string):Promise<void>;

export function UnarchiveWorkspace(arg1:string):Promise<worksetapi.WorkspaceRefJSON>;

export function UpdateAlias(arg1:main.AliasUpsertRequest):Promise<worksetapi.AliasMutationResultJSON>;

export function UpdateGroup(arg1:main.GroupUpsertRequest):Promise<worksetapi.GroupJSON>;

export function WriteWorkspaceTerminal(arg1:string,arg2:string,arg3:string):Promise<void>;
