version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - cyclop
    - gocognit
  settings:
    cyclop:
      max-complexity: 15
    gocognit:
      min-complexity: 25

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
