version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - cyclop
    - gocognit
  settings:
    cyclop:
      max-complexity: 18
    gocognit:
      min-complexity: 30
  exclusions:
    rules:
      - path: ".*_test\\.go$"
        linters:
          - cyclop
          - gocognit
      - path: "^cmd/workset/.*\\.go$"
        linters:
          - cyclop
          - gocognit

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
