const EXTENSION_ICON_MAP: Record<string, string> = {
	md: 'codicon:markdown',
	mdx: 'codicon:markdown',
	markdown: 'codicon:markdown',
	json: 'file-icons:json-1',
	jsonc: 'file-icons:json-1',
	json5: 'file-icons:json-1',
	yaml: 'file-icons:yaml',
	yml: 'file-icons:yaml',
	toml: 'file-icons:toml',
	ini: 'file-icons:config',
	conf: 'file-icons:config',
	config: 'file-icons:config',
	env: 'file-icons:config',
	editorconfig: 'file-icons:config',
	png: 'file-icons:image',
	jpg: 'file-icons:image',
	jpeg: 'file-icons:image',
	gif: 'file-icons:image',
	svg: 'file-icons:image',
	webp: 'file-icons:image',
	ico: 'file-icons:image',
	bmp: 'file-icons:image',
	zip: 'codicon:archive',
	tar: 'codicon:archive',
	gz: 'codicon:archive',
	rar: 'codicon:archive',
	'7z': 'codicon:archive',
	bz2: 'codicon:archive',
	xz: 'codicon:archive',
	csv: 'codicon:table',
	xlsx: 'codicon:table',
	xls: 'codicon:table',
	tsv: 'codicon:table',
	lock: 'codicon:lock',
	sum: 'codicon:lock',
	mod: 'codicon:lock',
	go: 'file-icons:go',
	ts: 'file-icons:typescript',
	tsx: 'file-icons:typescript',
	js: 'file-icons:javascript',
	jsx: 'file-icons:javascript',
	mjs: 'file-icons:javascript',
	cjs: 'file-icons:javascript',
	py: 'file-icons:python',
	rs: 'file-icons:rust',
	java: 'file-icons:java',
	kt: 'file-icons:kotlin',
	kts: 'file-icons:kotlin',
	swift: 'file-icons:swift',
	rb: 'file-icons:ruby',
	rake: 'file-icons:ruby',
	php: 'file-icons:php',
	c: 'file-icons:c',
	h: 'file-icons:c',
	cpp: 'file-icons:cpp',
	cc: 'file-icons:cpp',
	cxx: 'file-icons:cpp',
	hpp: 'file-icons:cpp',
	hxx: 'file-icons:cpp',
	cs: 'file-icons:csharp',
	scala: 'file-icons:scala',
	sc: 'file-icons:scala',
	lua: 'file-icons:lua',
	r: 'file-icons:r',
	sh: 'file-icons:terminal',
	bash: 'file-icons:terminal',
	zsh: 'file-icons:terminal',
	ps1: 'file-icons:powershell',
	psm1: 'file-icons:powershell',
	sql: 'codicon:database',
	tf: 'file-icons:terraform',
	tfvars: 'file-icons:terraform',
	vue: 'file-icons:vue',
	svelte: 'file-icons:svelte',
	css: 'file-icons:css',
	scss: 'file-icons:css',
	sass: 'file-icons:css',
	less: 'file-icons:css',
	html: 'file-icons:html',
	htm: 'file-icons:html',
	xml: 'file-icons:xml',
	xhtml: 'file-icons:xml',
	graphql: 'file-icons:graphql',
	gql: 'file-icons:graphql',
	proto: 'file-icons:proto',
	sol: 'file-icons:solidity',
	ex: 'file-icons:elixir',
	exs: 'file-icons:elixir',
	erl: 'file-icons:erlang',
	hs: 'file-icons:haskell',
	ml: 'file-icons:ocaml',
	mli: 'file-icons:ocaml',
	clj: 'file-icons:clojure',
	cljs: 'file-icons:clojure',
	lisp: 'file-icons:lisp',
	lsp: 'file-icons:lisp',
	dart: 'file-icons:dart',
	elm: 'file-icons:elm',
	fsharp: 'file-icons:fsharp',
	fs: 'file-icons:fsharp',
	vim: 'file-icons:vim',
	perl: 'file-icons:perl',
	pl: 'file-icons:perl',
	pm: 'file-icons:perl',
	awk: 'file-icons:awk',
	wasm: 'file-icons:wasm',
	dockerfile: 'file-icons:docker',
};

const PATH_SUFFIX_ICON_MAP: Record<string, string> = {
	'.tfcomponent.hcl': 'file-icons:terraform',
	'.tfdeploy.hcl': 'file-icons:terraform',
	'.tfquery.hcl': 'file-icons:terraform',
};

const FILE_NAME_ICON_MAP: Record<string, string> = {
	dockerfile: 'file-icons:docker',
	'go.mod': 'file-icons:go',
	'go.sum': 'file-icons:go',
	'go.work': 'file-icons:go',
	'go.work.sum': 'file-icons:go',
	makefile: 'file-icons:gnu',
	rakefile: 'file-icons:ruby',
	gemfile: 'file-icons:ruby',
	procfile: 'file-icons:config',
	license: 'codicon:law',
	readme: 'codicon:law',
	changelog: 'codicon:law',
	authors: 'codicon:law',
	contributors: 'codicon:law',
	gitignore: 'file-icons:git',
	gitattributes: 'file-icons:git',
	gitmodules: 'file-icons:git',
	npmrc: 'file-icons:npm',
	npmignore: 'file-icons:npm',
	eslintrc: 'file-icons:npm',
	prettierrc: 'file-icons:npm',
};

export const getRepoFileIcon = (path: string): string => {
	const ext = path.split('.').pop()?.toLowerCase() ?? '';
	const fileName = path.split('/').pop()?.toLowerCase() ?? '';
	const suffixIcon = Object.entries(PATH_SUFFIX_ICON_MAP).find(([suffix]) =>
		fileName.endsWith(suffix),
	)?.[1];
	return (
		suffixIcon ?? FILE_NAME_ICON_MAP[fileName] ?? EXTENSION_ICON_MAP[ext] ?? 'file-icons:default'
	);
};
